CurrencyBundle\Entity\Bank:
    type: entity
    table: banks
    repositoryClass: CurrencyBundle\Repository\BankRepository
    id:
        bank_id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            unique: true
        logo:
            type: string
            length: '4096'
        link:
            type: string
            length: '4096'
            nullable: true
    lifecycleCallbacks: {  }
