CurrencyBundle\Entity\Course:
    type: entity
    table: courses
    repositoryClass: CurrencyBundle\Repository\CourseRepository
    id:
        course_id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bank_id:
            type: integer
        currency:
            type: string
            length: '32'
        cost:
            type: float
        date:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        bank:
            targetEntity: CurrencyBundle\Entity\Bank
            joinColumn:
                name: bank_id
                referencedColumnName: bank_id
            cascade:
                - persist
