parameters:
    parsers:
        privatbank:
            title: Privatbank
            logo: "http://"
            link: "http://"
            class: "CurrencyBundle\\Parser\\PrivatbankParser"
        kredo:
            title: Kredo
            logo: "http://"
            link: "http://"
            class: "CurrencyBundle\\Parser\\KredoParser"
