services:
    app.command.course_update_command:
        class: "CurrencyBundle\\Command\\CourseUpdateCommand"
        tags:
            -
                name: "console.command"

    app.cors_listener:
        class: "CurrencyBundle\\Listener\\CorsListener"
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }